title: 초보 개발자
email: kjm1709@naver.com
description: >- 
  개발용 블로그 일지
# baseurl: "/" # the subpath of your site, e.g. /blog
# url: "http://ejjoo.github.io" # the base hostname & protocol for your site, e.g. http://example.com
github_username: ejjoo
highlighter: rouge
svg:
  optimize: true
highlighter-theme: monokai
#date_format: "%Y-%m-%d"
plugins:
  - jekyll-feed
  - jemoji
  - jekyll-collection-subdirs
category_dir: category/
tag_dir: tag/
livereload: true

exclude:
  - .sass-cache/
  - .jekyll-cache/
  - .idea/

kramdown:
  input: GFM  # GitHub Flavored Markdown을 사용하도록 설정

collections:
  Tip:
    output: true
    permalink: /Tip/:path/
    name: 팁
    icon: "아직 안정함"
    img: "테스트.jpg"
    order: 1