title: 초보 개발자
email: kjm1709@naver.com
description: >- 
  개발용 블로그 일지
# baseurl: "/" # the subpath of your site, e.g. /blog
# url: "http://ejjoo.github.io" # the base hostname & protocol for your site, e.g. http://example.com
github_username: ejjoo
highlighter: rouge
svg:
  optimize: true
highlighter-theme: monokai
date_format: "%Y-%M-%D"
plugins:
  - jekyll-feed
  - jemoji
category_dir: category/
tag_dir: tag/
livereload: true

exclude:
  - .sass-cache/
  - .jekyll-cache/
  - .idea/

include:
  - _pages
  - "netlify.toml"

kramdown:
  auto_ids: true

collections:
  project:
    output: true
    permalink: /Project/:path/
    name: 프로젝트
  Python:
    output: true
    permalink: /Python/:path/
    name: 파이썬
    emoji: ":snake:"
    order: 1
  EDA:
    output: true
    permalink: /EDA/:path/
    emoji: ":mag:"
    order: 2
  SQL:
    output: true
    permalink: /SQL/:path/
    emoji: ":floppy_disk:"
    order: 3
  Math:
    output: true
    permalink: /Math/:path/
    name: 수학
    emoji: ":heavy_division_sign:"
    order: 4
  Stastistics:
    output: true
    permalink: /Statistics/:path/
    name: 통계학
    emoji: ":bar_chart:"
    order: 5
  ML:
    output: true
    permalink: /ML/:path/
    name: 머신러닝
    emoji: ":robot:"
    order: 6