title: 두두닷의 개발블로그
email: kjm1709@naver.com
description: >-
  <img class="fox-image" src="/public/img/default/fox_icon.jpeg" alt="fox_icon" /> 두두닷
# baseurl: "/" # the subpath of your site, e.g. /blog
# url: "http://ejjoo.github.io" # the base hostname & protocol for your site, e.g. http://example.com
github_username: ejjoo
highlighter: rouge
svg:
  optimize: true
highlighter-theme: monokai
#date_format: "%Y-%m-%d"
plugins:
  - jekyll-feed
  - jemoji
category_dir: category/
tag_dir: tag/
livereload: true

exclude:
  - .sass-cache/
  - .jekyll-cache/
  - .idea/

kramdown:
  input: GFM  # GitHub Flavored Markdown을 사용하도록 설정

collections:
  Develop:
    output: true
    permalink: /Develop/:path/
    icon: "<i class='fa-brands fa-connectdevelop'></i>"
    order: 1
  DevOps:
    output: true
    permalink: /DevOps/:path/
    icon: "<i class='fa-solid fa-graduation-cap'></i>"
    order: 2
  DevKit:
    output: true
    permalink: /DevKit/:path/
    icon: "<i class='fa-solid fa-gear'></i>"
    order: 3
  Test:
    output: true
    permalink: /Test/:path/
    icon: "<i class='fa-brands fa-sketch'></i>"
    order: 4
